import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
#dimensions = { columns = 100, lines = 26 }
padding = { x = 8, y = 8 }
opacity = 0.9
blur = true
title = "Alacritty"
dynamic_title = false

[font]
normal = { family = "Hack Nerd Font", style = "Regular"}
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
size = 11

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = false
